name: Generar lista M3U

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

permissions:
  contents: write

jobs:
  generar:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Instalar dependencias
        run: npm install

      - name: Generar lista M3U
        env:
          PROVIDER_1_URL: ${{ secrets.PROVIDER_1_URL }}
          PROVIDER_2_URL: ${{ secrets.PROVIDER_2_URL }}
        run: node generar_lista.js

      - name: Verificar lista generada
        run: |
          test -f lista_limpia.m3u
          grep -q '^#EXTM3U' lista_limpia.m3u
          grep -q '^#EXTINF:' lista_limpia.m3u

          echo "=========================================="
          echo "M3U válido."
          echo "=========================================="

          echo "Cantidad de líneas:"
          wc -l lista_limpia.m3u

          echo "Primeras líneas:"
          head -n 10 lista_limpia.m3u

      - name: Publicar lista
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add lista_limpia.m3u

          if git diff --cached --quiet; then
            echo "No hubo cambios en la lista."
          else
            git commit -m "Actualizar lista M3U"
            git push
          fi
